---
# Visit https://goreleaser.com for documentation on how to customize this behavior.
project_name: "terraform-provider-netbox"
builds:
  - env:
      - "CGO_ENABLED=0"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w -X main.version={{ .Env.VER }} -X main.commit={{ .Commit }}"
    goos:
      - "windows"
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "386"
      - "arm64"
    ignore:
      - goos: "darwin"
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Env.VER }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Env.VER }}_SHA256SUMS"
  algorithm: "sha256"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
snapshot:
  name_template: "{{ .Env.VER }}"
env_files:
  github_token: "~/.config/goreleaser/github_token"
