---
# Visit https://goreleaser.com for documentation on how to customize this behavior.
project_name: "terraform-provider-netbox"
builds:
  - env:
      - "CGO_ENABLED=0"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w -X main.version={{ .Env.VER }} -X main.commit={{ .Commit }}"
    goos:
      - "windows"
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "386"
      - "arm64"
    ignore:
      - goos: "darwin"
        goarch: "386"
    binary: "{{ .ProjectName }}_{{ .Env.VER }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Env.VER }}_SHA256SUMS"
  algorithm: "sha256"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Env.VER }}_{{ .Os }}_{{ .Arch }}"
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  github:
    owner: "josh-silvas"
    name: "terraform-provider-netbox"
  name_template: "{{ .Tag }}"
  draft: false
changelog:
  skip: true
snapshot:
  name_template: "{{ .Env.VER }}"
env_files:
  github_token: "~/.config/goreleaser/github_token"
