---
version: "3.7"
services:

  postgres:
    image: "postgres:12-alpine"
    env_file:
      - ".env"

  redis:
    image: "redis:6-alpine"

  netbox:
    image: "netboxcommunity/netbox:${NETBOX_VERSION}"
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "8001:8080"
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: "10s"
      timeout: "10s"
      retries: 10
      start_period: "5s"
